create database dwd;

create table dwd.dwd_stocks_quotes_di (
trading_date    string comment '股票交易日' 
,market  string comment '市场'
,stocks_code    string comment '股票编码'
,stocks_name  string comment '股票名称'
,listing_date  string comment '上市日期'
,request_status string comment '请求状态码'
,quotes_data    string comment '股票行情'
,create_time    string comment '创建时间'
,update_time    string comment '修改时间'
,ytd_closing_price decimal(18,2) comment '昨收'
,today_opening_price decimal(18,2) comment '今开'
,today_closing_price decimal(18,2) comment '今收'
,rose_percent decimal(18,2) comment '涨幅%'
,rose_price decimal(18,2) comment '涨跌'
,limit_up decimal(18,2) comment '涨停'
,limit_down decimal(18,2) comment '跌停'
,high_price decimal(18,2) comment '最高'
,low_price decimal(18,2) comment '最低'
,avg_price decimal(18,2) comment '均价' 
,amplitude_percent decimal(18,2) comment '振幅%' 
,deal_cnt bigint comment '成交量'
,deal_amt decimal(18,2) comment '成交额' 
,turnover_rate decimal(18,2) comment '换手%'
,per_static decimal(18,2) comment '市盈率(静)'
,per_moving decimal(18,2) comment '市盈率(动)'
,per_ttm decimal(18,2) comment '滚动市盈率(TTM)'
,pbr decimal(18,2) comment '市净率'
,market_cap decimal(18,2) comment '总市值'
,float_cap decimal(18,2) comment '流通市值'
,total_equity decimal(18,2) comment '总股本'
,float_stock decimal(18,2) comment '流通股'
,after_hours_deal_cnt bigint comment '盘后成交量'
,after_hours_deal_amt decimal(18,2) comment '盘后成交额'
,super_inflow_amt decimal(18,2) comment '超大单流入金额'
,big_inflow_amt decimal(18,2) comment '大单流入金额'
,mid_inflow_amt decimal(18,2) comment '中单流入金额'
,small_inflow_amt decimal(18,2) comment '小单流入金额'
,super_outflow_amt decimal(18,2) comment '超大单流出金额'
,big_outflow_amt decimal(18,2) comment '大单流出金额'
,mid_outflow_amt decimal(18,2) comment '中单流出金额'
,small_outflow_amt decimal(18,2) comment '小单流出金额'
,big_net_amt decimal(18,2) comment '主力净额（大单流入金额减大单流出金额）'
,net_inflow_amt decimal(18,2) comment '资金净流入(流入金额减流出金额)'
,appoint_rate decimal(18,2) comment '委比%'
,appoint_diff bigint comment '委差'
,highest_buy_price decimal(18,2) comment '买一价格'
,hightest_buy_cnt bigint comment '买一委托量'
,highest_sale_price decimal(18,2) comment '卖一价格'
,highest_sale_cnt bigint comment '卖一委托量'
,outside_dish bigint comment '外盘'
,inside_dish bigint comment '内盘'
)
PARTITIONED BY (pt string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\u0001'
STORED AS ORC;
